### ISSUE TITLE
Feature Suggest: Support pattern array

### ISSUE THREAD

**Issue by banyudu** [lionel-rowe/browser-extension-url-match#1]
Browser Extension match patterns could be an array of patterns, for example, `host_permissions` in the `manifest.json`.

Without array support, to process a pattern array one needs to wrap this library:

```js
const matchers = patterns.map(item => matchPattern(item))

const matcher = url => matchers.some(item => item.match(url))
```

Could you support array directly in this lib?

```js

import { matchPattern } from 'browser-extension-url-match'

const matcher = matchPattern([
  'https://example.com/foo/*',
  'https://example.com/foo2/*',
])

matcher.match('https://example.com/foo/bar')
// ⇒ true
matcher.match('https://example.com/foo2/bar')
// ⇒ true
matcher.match('https://example.com/bar/baz')
// ⇒ false

```

**Comment by lionel-rowe** [comment]
Makes sense — in fact, I think there are a few less-than-ideal things about the API, so I'll probably add this in along with a few breaking changes. The big one is that `matchPattern(...some invalid pattern...)` shouldn't transparently allow `match` to be used and always return `false`, as matching could be used for blacklists as well as whitelists.

With the upcoming change, you'll have to use some custom type guards or assert that the matcher is valid in TypeScript. So all-in-all, the new API will look like this:

```ts
const matcher = matchPattern([
    'https://example.com/foo/*',
    'https://example.com/foo2/*',
])

matcher.valid
// ⇒ true
matcher.error
// ⇒ undefined
matcher.match('https://example.com/foo/bar')
// Property 'match' does not exist on type 'MatcherOrInvalid'.
// Property 'match' does not exist on type 'InvalidMatcher'.

if (matcher.valid) {
    matcher.match('https://example.com/foo/bar')
    // ⇒ true (OK due to type guard)
}

matcher.assertValid().match('https://example.com/foo/bar')
// ⇒ true (OK due to calling assertValid on a valid matcher)

const invalidMatcher = matchPattern([
    'https://example.com/foo/*',
    'https://example.com',
])

invalidMatcher.valid
// ⇒ false
invalidMatcher.error
// ⇒ Error: Pattern "https://example.com" needs a trailing slash to be valid (should be "https://example.com/")

if (invalidMatcher.valid) {
    matcher.match('https://example.com/foo/bar')
    // code path is never executed
}

invalidMatcher.assertValid().match('https://example.com/foo/bar')
// assertValid throws TypeError at runtime due to being called on an invalid matcher
```

**Comment by Sec-ant** [comment]
Hey @lionel-rowe , do you have any ETA on this new API? I plan to use this package and would like to have some anticipation or preparation for the breaking changes. Thx!

**Comment by lionel-rowe** [comment]
@Sec-ant should be sometime this weekend.

**Comment by lionel-rowe** [comment]
Version 1.0.0 is out now, containing the new API (I went with `assertValid` instead of `unwrap`) and a few bugfixes. Details in the updated README.
